// BravusApp/src/components/Home.vue
<template>
  <section>
    <h1>Welcome To Bravus</h1>
    <p>Making organizing easy for small business</p>
    <form>
      <div>
        <label> Give it a Try </label>
        <input type="email">
      </div>
    </form>
  </section>
  <section>
    <h2> About Us </h2>
    <p>
      Hi, my name is Aramis Martinez. I'm a student trying to make a tool that combines elements of different apps out there.
      I got this idea after my ant start to have problems organizing her small business. She's a chiropractor, who wanted to 
      be able to make the process of making appointments easier on her. She also wanted to be able to track thing like her inventories.
      Yes she could use things like booksy for appontments and for the other stuff she could use a sheets app like google sheets.
      But I believe an app that can do all that in one place has alot of value so I setoff on making Bravus.
    </p>
  </section>
  <section>
    <h2> Our Goal </h2>
    <p> 
      Bravus is a simple dashboard that aim to have small appointment based business.
      We achive this by allowing Owners of the business control and manage key things on the dashboard.
      We first give them a platform where they can take client to make and manage profile that they can use
      to make appointments with the owners. We also give that a way for them to manage their inventories and 
      financials.
    </p>
  </section>
  <section>
    <h2> Bravus Main Features </h2>
    <p>
      These are the main features of Bravus.
    </p>
    <h3> Business management tools </h3>
    <p>
      First, Goes the business management tools. The main tool we have is the sheets/tables system.
      This system allow for creating or importing a google sheets for the use of financial management or inventory 
      management. This sysyem also allow for the information in these sheet to make graphic that can be personalized.
    </p>
    <h3> Calander updates </h3>
    <p>
      This feature is simple. We allow owners to see their appointments on their google calander. This also will show if 
      an appointment get canceled. With the help of this system we also allow owners to select their open time for appointments
    </p>
    <h3> Appointments controls </h3>
    <p>
      Here we get to the main appointment control system. This feature allow for the management of appointment. For example if the owner 
      can't make it to the appointment they can cancel and it will notifies the client. Otherwise this system is where the owner would select 
      there days off.
    </p>
  </section>
  <section>
    <h2> Contact Us </h2>
    <p>
      If anyone one has any question you can contact me at -blank
    </p>
    <form>
      <label> Reason or question </label>
      <input type="text" />
      <label> Extra information </label>
      <input type="text" />
      <button type="submit"> Submit </button>
    </form>
  </section>
</template>

// src/pages/Home.jsx
import React from "react";

function Home() {
    return (
        <div className='color: text-main-white'>
            <section>
                <h1>Welcome To Bravus</h1>
                <p>Making organizing easy for small business</p>
                <form>
                <div>
                    <label> Give it a Try </label>
                    <input type="email"/>
                </div>
                </form>
            </section>
            <section>
                <h2> About Us </h2>
                <p>
                Hi, my name is Aramis Martinez. I'm a student trying to make a tool that combines elements of different apps out there.
                I got this idea after my ant start to have problems organizing her small business. She's a chiropractor, who wanted to 
                be able to make the process of making appointments easier on her. She also wanted to be able to track thing like her inventories.
                Yes she could use things like booksy for appontments and for the other stuff she could use a sheets app like google sheets.
                But I believe an app that can do all that in one place has alot of value so I setoff on making Bravus.
                </p>
            </section>
            <section>
                <h2> Our Goal </h2>
                <p> 
                Bravus is a simple dashboard that aim to have small appointment based business.
                We achive this by allowing Owners of the business control and manage key things on the dashboard.
                We first give them a platform where they can take client to make and manage profile that they can use
                to make appointments with the owners. We also give that a way for them to manage their inventories and 
                financials.
                </p>
            </section>
            <section>
                <h2> Bravus Main Features </h2>
                <p>
                These are the main features of Bravus.
                </p>
                <h3> Business management tools </h3>
                <p>
                First, Goes the business management tools. The main tool we have is the sheets/tables system.
                This system allow for creating or importing a google sheets for the use of financial management or inventory 
                management. This sysyem also allow for the information in these sheet to make graphic that can be personalized.
                </p>
                <h3> Calander updates </h3>
                <p>
                This feature is simple. We allow owners to see their appointments on their google calander. This also will show if 
                an appointment get canceled. With the help of this system we also allow owners to select their open time for appointments
                </p>
                <h3> Appointments controls </h3>
                <p>
                Here we get to the main appointment control system. This feature allow for the management of appointment. For example if the owner 
                can't make it to the appointment they can cancel and it will notifies the client. Otherwise this system is where the owner would select 
                there days off.
                </p>
            </section>
            <section>
                <h2> Contact Us </h2>
                <p>
                If anyone one has any question you can contact me at -blank
                </p>
                <form>
                <label> Reason or question </label>
                <input type="text" />
                <label> Extra information </label>
                <input type="text" />
                <button type="submit"> Submit </button>
                </form>
            </section>
        </div>
    )
};

export default Home;
